/**
 * Antigravity Workflow Runtime — 错误码定义
 */

export enum WorkflowErrorCode {
  // 通用错误 (1xxx)
  INTERNAL_ERROR = 'WORKFLOW_1000',
  INVALID_INPUT = 'WORKFLOW_1001',
  NOT_FOUND = 'WORKFLOW_1002',

  // DAG 错误 (2xxx)
  GRAPH_CYCLE_DETECTED = 'WORKFLOW_2001',
  GRAPH_INVALID_EDGE = 'WORKFLOW_2002',
  GRAPH_NODE_NOT_FOUND = 'WORKFLOW_2003',
  GRAPH_EMPTY = 'WORKFLOW_2004',

  // 合规错误 (3xxx)
  COMPLIANCE_BLOCKED = 'WORKFLOW_3001',
  COMPLIANCE_RULE_ERROR = 'WORKFLOW_3002',

  // 风险错误 (4xxx)
  RISK_ASSESSMENT_FAILED = 'WORKFLOW_4001',

  // 状态错误 (5xxx)
  STATE_VERSION_CONFLICT = 'WORKFLOW_5001',
  EVENT_STORE_ERROR = 'WORKFLOW_5002',
  CHECKPOINT_ERROR = 'WORKFLOW_5003',

  // 验证错误 (6xxx)
  VERIFY_DRIFT_DETECTED = 'WORKFLOW_6001',
  VERIFY_REPLAY_MISMATCH = 'WORKFLOW_6002',
}
